[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = false

[theme]
primaryColor = "#4CAF50"
backgroundColor = "#f0f2f6"
secondaryBackgroundColor = "#e0e0e0"
textColor = "#333333"
font = "sans serif"

